language: perl
perl:
  - "5.14"
  - "5.20"
  - "5.26"
  - "5.30"
  - "dev"
sudo: false             # faster builds as long as you don't need sudo access
before_install:
  - export DIST_INKT_PROFILE="Dist::Inkt::Profile::TOBYINK"
  - eval $(curl https://travis-perl.github.io/init) --auto
  - perl -v


